# -*- coding: utf-8 -*-
"""generate_kpis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NheMwiu6sRT3nn7itTP8XPZeVr9gQqDI
"""

import pandas as pd
import numpy as np

!pip install xlsxwriter

def generate_kpis(input_csv_path, output_excel_path):
    # Load the military_cleaned.csv file into a DataFrame
    df = pd.read_csv(input_csv_path)

    # Calculate intermediate metric: total_assets
    df['total_assets'] = df['total_aircraft'] + df['tanks'] + df['naval_assets']

    # If 'coalition_strength_index' column exists, remove it (to ensure clean recalculation if script is re-run)
    if 'coalition_strength_index' in df.columns:
        df = df.drop(columns=['coalition_strength_index'])

    # Define KPI columns for the 9 per-country KPIs
    kpi_columns = [
        'assets_per_capita',
        'defense_budget_to_gdp_ratio',
        'personnel_density',
        'defense_budget_per_soldier',
        'power_index_rank_gap',
        'air_power_ratio',
        'armor_intensity_index',
        'naval_strength_per_coastline',
        'military_burden_index'
    ]

    # Calculate per-country KPIs
    df['assets_per_capita'] = df['total_assets'] / df['population']
    df['defense_budget_to_gdp_ratio'] = df['defense_budget_usd'] / df['gdp_usd']
    df['personnel_density'] = df['total_personnel'] / df['population']
    df['defense_budget_per_soldier'] = df['defense_budget_usd'] / df['active_personnel']

    # Power Index Rank Gap: Reference rank 1
    rank_1_country_df = df[df['power_index_rank'] == 1]
    if not rank_1_country_df.empty:
        rank_1_value = rank_1_country_df['power_index_rank'].iloc[0]
        df['power_index_rank_gap'] = df['power_index_rank'] - rank_1_value
    else:
        df['power_index_rank_gap'] = np.nan # If no rank 1 country, set to NaN

    df['air_power_ratio'] = df['total_aircraft'] / df['active_personnel']
    df['armor_intensity_index'] = df['tanks'] / df['land_area_sq_km']
    df['naval_strength_per_coastline'] = df['naval_assets'] / df['coastline_km']
    df['military_burden_index'] = df['defense_budget_usd'] / df['population']

    # Calculate Alliance-Based Coalition Strength Index
    alliance_total_assets = df.groupby('alliance')['total_assets'].sum()
    df['alliance_based_coalition_strength_index'] = df['alliance'].map(alliance_total_assets)
    df.loc[df['alliance'] == 'Other', 'alliance_based_coalition_strength_index'] =         df.loc[df['alliance'] == 'Other', 'total_assets']

    # Add new KPI to the list
    kpi_columns.append('alliance_based_coalition_strength_index')

    # Replace infinite values with NaN for all newly created KPI columns
    for col in kpi_columns:
        df[col] = df[col].replace([np.inf, -np.inf], np.nan)

    # Define relevant original features and metadata columns
    relevant_original_features = [
        'population', 'total_personnel', 'active_personnel', 'total_aircraft',
        'tanks', 'naval_assets', 'defense_budget_usd', 'gdp_usd',
        'land_area_sq_km', 'coastline_km', 'power_index_rank', 'total_assets'
    ]
    metadata_columns = ['region', 'continent', 'alliance']

    # Create wide-format DataFrame
    all_columns_for_wide_df = ['country'] + relevant_original_features + kpi_columns + metadata_columns
    df_wide = df[all_columns_for_wide_df].copy()

    # Create long-format DataFrame
    df_long = df_wide.melt(id_vars=['country', 'region', 'continent', 'alliance'],
                           value_vars=kpi_columns,
                           var_name='KPI',
                           value_name='Value')

    # Save DataFrames to Excel
    with pd.ExcelWriter(output_excel_path, engine='xlsxwriter') as writer:
        df_wide.to_excel(writer, sheet_name='Wide Format KPIs', index=False)
        df_long.to_excel(writer, sheet_name='Long Format KPIs', index=False)

    print(f"KPIs generated and saved to '{output_excel_path}'")

if __name__ == '__main__':
    # Example usage: Ensure these paths are correct for your environment
    input_csv = '/content/military_cleaned.csv'
    output_excel = 'military_final.xlsx'
    generate_kpis(input_csv, output_excel)