# -*- coding: utf-8 -*-
"""generate_kpis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qbNPIuaAdJwUDt-POGYfQiz1lma364b3
"""

import pandas as pd
import numpy as np

pip install wbdata

df = pd.read_csv('military_cleaned (2).csv')

df["year"] = 2025

nato_countries = [
    "United States","United Kingdom","France","Germany","Italy","Spain",
    "Canada","Poland","Netherlands","Belgium","Portugal","Denmark",
    "Norway","Greece","Turkey","Czechia","Hungary","Bulgaria",
    "Romania","Slovakia","Slovenia","Croatia","Albania",
    "Lithuania","Latvia","Estonia","Luxembourg","Iceland",
    "North Macedonia"
]

df["alliance"] = "Others"
df.loc[df["country"].isin(nato_countries), "alliance"] = "NATO"
df.loc[~df["country"].isin(nato_countries), "alliance"] = "Non-NATO"

continent_map = {
    # Asia
    "China":"Asia","India":"Asia","Indonesia":"Asia","Pakistan":"Asia","Bangladesh":"Asia",
    "Japan":"Asia","Philippines":"Asia","Vietnam":"Asia","Iran":"Asia","Turkiye":"Asia",
    "Thailand":"Asia","South Korea":"Asia","North Korea":"Asia","Sri Lanka":"Asia",
    "Nepal":"Asia","Malaysia":"Asia","Cambodia":"Asia","Laos":"Asia","Mongolia":"Asia",
    "Kazakhstan":"Asia","Uzbekistan":"Asia","Turkmenistan":"Asia","Tajikistan":"Asia",
    "Kyrgyzstan":"Asia","Iraq":"Asia","Afghanistan":"Asia","Saudi Arabia":"Asia",
    "Israel":"Asia","Jordan":"Asia","Lebanon":"Asia","Oman":"Asia","Kuwait":"Asia",
    "Qatar":"Asia","Bahrain":"Asia","United Arab Emirates":"Asia","Taiwan":"Asia",
    "Georgia":"Asia","Armenia":"Asia","Azerbaijan":"Asia",

    # Europe
    "Russia":"Europe","Germany":"Europe","United Kingdom":"Europe","France":"Europe",
    "Italy":"Europe","Spain":"Europe","Poland":"Europe","Ukraine":"Europe","Romania":"Europe",
    "Netherlands":"Europe","Belgium":"Europe","Portugal":"Europe","Sweden":"Europe",
    "Greece":"Europe","Austria":"Europe","Switzerland":"Europe","Ireland":"Europe",
    "Norway":"Europe","Finland":"Europe","Denmark":"Europe","Slovakia":"Europe",
    "Slovenia":"Europe","Croatia":"Europe","Hungary":"Europe","Bulgaria":"Europe",
    "Serbia":"Europe","Bosnia and Herzegovina":"Europe","Moldova":"Europe",
    "Albania":"Europe","Lithuania":"Europe","Latvia":"Europe","Estonia":"Europe",
    "Luxembourg":"Europe","Iceland":"Europe","Montenegro":"Europe","Kosovo":"Europe",

    # Africa
    "Nigeria":"Africa","Ethiopia":"Africa","Egypt":"Africa","South Africa":"Africa",
    "Kenya":"Africa","Sudan":"Africa","Uganda":"Africa","Algeria":"Africa","Morocco":"Africa",
    "Angola":"Africa","Ghana":"Africa","Mozambique":"Africa","Cameroon":"Africa",
    "Ivory Coast":"Africa","Madagascar":"Africa","Niger":"Africa","Mali":"Africa",
    "Burkina Faso":"Africa","Chad":"Africa","Senegal":"Africa","Benin":"Africa",
    "Somalia":"Africa","South Sudan":"Africa","Tunisia":"Africa","Libya":"Africa",
    "Eritrea":"Africa","Central African Republic":"Africa","Liberia":"Africa",
    "Mauritania":"Africa","Gabon":"Africa","Botswana":"Africa","Namibia":"Africa",

    # Americas
    "United States":"North America","Canada":"North America","Mexico":"North America",
    "Guatemala":"North America","Honduras":"North America","Nicaragua":"North America",
    "El Salvador":"North America","Panama":"North America","Cuba":"North America",
    "Dominican Republic":"North America","Beliz":"North America",

    "Brazil":"South America","Colombia":"South America","Argentina":"South America",
    "Peru":"South America","Chile":"South America","Ecuador":"South America",
    "Bolivia":"South America","Paraguay":"South America","Uruguay":"South America",
    "Venezuela":"South America","Suriname":"South America",

    # Oceania
    "Australia":"Oceania","New Zealand":"Oceania"
}

df["continent"] = df["country"].map(continent_map)

region_map = {
    "India":"South Asia","Pakistan":"South Asia","Bangladesh":"South Asia","Sri Lanka":"South Asia","Nepal":"South Asia",
    "China":"East Asia","Japan":"East Asia","South Korea":"East Asia","North Korea":"East Asia","Taiwan":"East Asia",
    "Indonesia":"Southeast Asia","Vietnam":"Southeast Asia","Thailand":"Southeast Asia","Malaysia":"Southeast Asia","Philippines":"Southeast Asia","Cambodia":"Southeast Asia","Laos":"Southeast Asia",
    "Iran":"Middle East","Iraq":"Middle East","Saudi Arabia":"Middle East","Israel":"Middle East","Jordan":"Middle East","Lebanon":"Middle East","Oman":"Middle East","Kuwait":"Middle East","Qatar":"Middle East","Bahrain":"Middle East","United Arab Emirates":"Middle East",
    "Germany":"Western Europe","France":"Western Europe","United Kingdom":"Western Europe","Italy":"Western Europe","Spain":"Western Europe","Netherlands":"Western Europe","Belgium":"Western Europe","Portugal":"Western Europe","Austria":"Western Europe","Switzerland":"Western Europe",
    "Poland":"Eastern Europe","Ukraine":"Eastern Europe","Russia":"Eastern Europe","Romania":"Eastern Europe","Hungary":"Eastern Europe","Bulgaria":"Eastern Europe","Serbia":"Eastern Europe",
    "Nigeria":"Sub-Saharan Africa","Kenya":"Sub-Saharan Africa","Ghana":"Sub-Saharan Africa","South Africa":"Sub-Saharan Africa","Ethiopia":"Sub-Saharan Africa",
    "Egypt":"North Africa","Algeria":"North Africa","Morocco":"North Africa","Tunisia":"North Africa","Libya":"North Africa",
    "United States":"North America","Canada":"North America","Mexico":"North America",
    "Brazil":"South America","Argentina":"South America","Chile":"South America","Peru":"South America","Colombia":"South America",
    "Australia":"Oceania","New Zealand":"Oceania"
}

df["region"] = df["country"].map(region_map)

df.head()

df = df.rename(columns={
    "capital": "capital_city",
    "total_population_by_country": "population",
    "active_military_manpower": "active_personnel",
    "active_reserve_military_manpower": "reserve_personnel",
    "aircraft_total": "total_aircraft",
    "aircraft_total_fighters": "fighter_aircraft",
    "aircraft_total_attack_types": "attack_aircraft",
    "aircraft_total_transports": "transport_aircraft",
    "aircraft_helicopters_total": "helicopters",
    "armor_tanks_total": "tanks",
    "armor_apc_total": "armored_vehicles",
    "armor_towed_artillery_total": "artillery_units",
    "navy_aircraft_carriers": "aircraft_carriers",
    "defense_spending_budget": "defense_budget_usd",
    "square_land_area": "land_area_sq_km",
    "coastline_coverage": "coastline_km"
})

import wbdata
import pandas as pd
import datetime

# World Bank indicator
indicator = {"NY.GDP.MKTP.CD": "gdp_usd"}

# Get latest available year
data_date = datetime.datetime(2023, 1, 1)

# Fetch GDP data
gdp_data = wbdata.get_dataframe(indicator  )

# Reset index
gdp_data = gdp_data.reset_index()

# Rename country column
gdp_data.rename(columns={"country": "country"}, inplace=True)
gdp_clean = gdp_data.groupby("country", as_index=False)["gdp_usd"].max()

# Merge with your dataset
df = df.merge(gdp_clean, on="country", how="left")

missing_gdp = df[df["gdp_usd"].isna()]["country"]

print("Missing GDP count:", missing_gdp.shape[0])
missing_gdp.tolist()

gdp_mapping_18 = {
    # World Bank (name-mismatch fixed)
    "Egypt": 389000000000,                          # Egypt, Arab Rep.
    "Vietnam": 476000000000,                        # Viet Nam
    "Democratic Republic of the Congo": 164000000000,  # Congo, Dem. Rep.
    "Somalia": 26700000000,                         # Somalia

    # World Bank (direct / corrected names)
    "Ivory Coast": 87113180000,                     # Cote d'Ivoire
    "Beliz": 3203632000,                            # Belize
    "Republic of the Congo": 15719990000,           # Congo, Rep.
    "Kyrgyzstan": 17478260000,
    "Laos": 16502930000,
    "Slovakia": 140934100000,
    "Venezuela": 119803000000,
    "Yemen": 21606160000,
    "South Korea": 1875388000000,

    # Non–World Bank (IMF / CIA)
    "Russia": 2380000000000,                        # IMF WEO
    "Iran": 1490000000000,                          # IMF WEO
    "Taiwan": 900000000000,                         # IMF / Taiwan stats
    "North Korea": 15000000000,                     # CIA Factbook
    "Syria": 23622830000                            # UN / IMF estimates
}

df["gdp_usd"] = df["country"].map(gdp_mapping_18).fillna(df["gdp_usd"])

df['gdp_usd'].isna().sum()

df.to_csv('military_csv_with_metadata.csv', index=False)

"""**KPIs**"""

df["power_index_rank_gap"] = df["power_index_rank"] - 1

df[["country", "power_index_rank", "power_index_rank_gap"]].head(10)

navy_cols = [
    "navy_ships",
    "navy_submarines",
    "navy_destroyers",
    "navy_frigates",
    "navy_corvettes",
    "navy_patrol_coastal_craft",
    "navy_mine_warfare_craft",
    "aircraft_carriers",
    "navy_helo_carriers"
]
df["naval_assets"] = df[navy_cols].sum(axis=1)

# Total military assets
df["total_military_assets"] = (
    df["total_aircraft"]
    + df["tanks"]
    + df["armored_vehicles"]
    + df["artillery_units"]

)

df["assets_per_capita"] = df["total_military_assets"]+df["naval_assets"] / df["population"]

df[["country", "assets_per_capita"]].head()

df["budget_to_gdp_ratio"] = df["defense_budget_usd"] / df["gdp_usd"]
df["budget_to_gdp_percent"] = df["budget_to_gdp_ratio"] * 100

df[["country", "defense_budget_usd", "gdp_usd", "budget_to_gdp_percent"]].head()

df.to_csv('military_data_with_KPIs.csv')

wide_cols = [
    "country",
    "region",
    "continent",
    "alliance",
    "year",

    # KPIs
    "power_index_rank_gap",
    "assets_per_capita",
    "budget_to_gdp_percent"
]

df_wide = df[wide_cols].copy()

df_wide.to_csv("kpis_wide.csv", index=False)

id_cols = [
    "country",
    "region",
    "continent",
    "alliance",
    "year"
]
kpi_cols = [
    "power_index_rank_gap",
    "assets_per_capita",
    "budget_to_gdp_percent"
]

df_long = df_wide.melt(
    id_vars=id_cols,
    value_vars=kpi_cols,
    var_name="kpi_name",
    value_name="kpi_value"
)

df_long["kpi_name"] = pd.Categorical(
    df_long["kpi_name"],
    categories=kpi_cols,
    ordered=True
)

df_long = df_long.sort_values(
    by=["country", "kpi_name"]
).reset_index(drop=True)

df_long.head(9)

df_long.to_csv("kpis_long.csv", index=False)