# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K0di7Hk3VA1MbDUbY3J_O1X--Ne1KZT4
"""

import pandas as pd
import numpy as np

"""# **Extracting Links from the txt file**"""

links=[]
with open('all_ links_for_global_military_data.txt', 'r') as f:
    linkss = f.readlines()
    for  i in linkss:
        links.append(i.strip()[1:])

"""# **Extracting the html contents from the links using BeautifulSoup**

Checking the html content of first link
"""

import requests
from bs4 import BeautifulSoup


response= requests.get(links[0])
soup =BeautifulSoup(response.content,'html.parser')

print(soup.prettify())

countries=[]

links.remove("https://www.globalfirepower.com/capital-cities-by-total-population.php")

"""Data(dict) is created by  extracting the value for each country (Value and Country names are extracted using their divs from the html )and the metric name is directly derived from the link"""

import requests
from bs4 import BeautifulSoup
import time

headers = {"User-Agent": "Mozilla/5.0"}
data = {}

for url in links:

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    metric=url.split("/")[-1].split(".")[0]
    rows = soup.select("div.picTrans.recordsetContainer")

    for row in rows:
        country = row.select_one(
            "div.countryNameContainer span.textWhite"
        )


        value = row.select_one(
            "div.valueContainer span span"
        )

        if not country or not value:
            continue

        cname = country.text.strip()
        val = value.text.strip()
        if cname not in data:
            data[cname] = {}
            countries.append(cname)

        data[cname][metric] = val

"""Handling the Capital Case seperately because the country name is not mentioned only in this capital_cities_population"""

i=0
response = requests.get("https://www.globalfirepower.com/capital-cities-by-total-population.php", headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

rows = soup.select("div.picTrans.recordsetContainer")
for row in  rows:
        capital = row.select_one(
            "div.countryNameContainer span.textWhite"
        )
        value = row.select_one(
            "div.valueContainer span span"
        )

        data[countries[i]]['Capital']=capital.text.strip()

        data[countries[i]]['Captal Population']=value.text.strip()
        i+=1

"""# **Converting it into the Dataframe and then to csv**"""

df = pd.DataFrame.from_dict(data, orient="index")
df.index.name = "Country"
df.reset_index(inplace=True)
df.to_csv("countries_data.csv", index=False)

df.head()